# Basic docker-compose.yml running the project as docker container.

services:
  discord-tts-bot:
    image: discord-tts-bot:latest
    build: .
    container_name: discord-tts-bot
    restart: unless-stopped
    volumes:
      - ./persistency:/app/persistency
    environment:
      # Mandatory Discord bot token.
      - DISCORD_BOT_TOKEN=
      # Mandatory language code used for TTS, check gTTS documentation for details.
      - TEXT_LANGUAGE=en
      # File used for storing channel data between bot restarts.
      # Both files are stored in a mounted volume, so they should survive recreating the container.
      - SOURCE_CHANNELS_FILE=./persistency/sources
      - TARGET_CHANNEL_FILE=./persistency/target
      # Optional voice file path.
      # Here gTTS will store converted audio files, which will be later read out.
      # Doesn't matter much when it comes to Docker container.
      # - VOICE_FILE_PATH=voice_file.mp3
networks:
  default:
    name: discord-tts-bot-network
    driver: bridge
